autowarefoundation/autoware_common

- .github/workflows/pre-commit.yaml
Actually, we don't need this for this repository since we use pre-commit.ci, but I'll add this to copy to other repositories by [sync-files action](https://github.com/autowarefoundation/autoware-github-actions/pull/26).
> ci: add pre-commit.yaml

- .github/sync-files.yaml
To import the changes made in `autoware.universe`, I'll add a cross-reference.
> chore: sync autoware.universe

- .github/workflows/build-and-test-pr.yaml
- .github/workflows/build-and-test.yaml
Changed so that the CodeCov uploader does not throw an error when the upload fails.
This avoids problems when private repositories want to build using this workflow, but do not want to use CodeCov.
Signed-off-by: Keisuke Shima <19993104+KeisukeShima@users.noreply.github.com>
> ci(build-and-test): ignore CodeCov errors

- .github/workflows/build-and-test-self-hosted.yaml
- .github/workflows/build-and-test.yaml
Resolves this error: https://github.com/autowarefoundation/autoware-github-actions/pull/68/files#r804486016
> ci(build-and-test): do not run if no package was found

- .github/workflows/check-build-depends.yaml
Since this workflow just checks the build, the `Test` job isn't necessary.
> ci(check-build-depends): remove tests to make it faster

- autoware_cmake/CMakeLists.txt
- autoware_cmake/cmake/autoware_package.cmake
- autoware_lint_common/CMakeLists.txt
Defined a macro `BOOST_ALLOW_DEPRECATED_HEADERS` to ignore Boost deprecated messages.
According to [this comment](https://stackoverflow.com/questions/66906613/how-to-silence-internal-boost-deprecated-messages#comment118269576_66906613), it seems there are no other ways for now? :thinking: 
References:
- https://www.boost.org/doc/libs/1_68_0/libs/config/doc/html/boost_config/boost_macro_reference.html
- https://stackoverflow.com/questions/66906613/how-to-silence-internal-boost-deprecated-messages
Also, `add_definitions` was replaced by `add_compile_definitions`
https://cmake.org/cmake/help/latest/command/add_definitions.html
Related: https://github.com/autowarefoundation/autoware.universe/pull/856
The PR reviewers …
> feat(autoware_cmake): ignore Boost deprecated messages

- autoware_cmake/cmake/autoware_package.cmake
Ignored this kind of warning.
```
--- stderr: tier4_system_launch
CMake Warning:
Manually-specified variables were not used by the project:
CMAKE_EXPORT_COMPILE_COMMANDS
```
Reference: https://stackoverflow.com/questions/36451368/get-rid-of-cmake-warning-manually-specified-variables-were-not-used-by-the-proj
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/cont …
> chore: ignore unnecessary CMake warnings

- .github/sync-files.yaml
Sync https://github.com/autowarefoundation/autoware/blob/main/.clang-tidy for local development.
Regarding CI, it's already used. https://github.com/autowarefoundation/autoware_common/blob/6bba407da4448c41d0e532b5f15d9cf262d5dff7/.github/workflows/build-and-test-differential.yaml#L88
Merge after https://github.com/autowarefoundation/autoware/pull/2763.
> ci(sync-files): sync .clang-tidy

- tmp/lanelet2_extension/docs/lanelet2_format_extension.md
Signed-off-by: Mehmet Dogru <42mehmetdogru42@gmail.com>
Related to https://github.com/autowarefoundation/autoware.universe/pull/1528
This PR adds instructions to `lanelet2_extension` about safety slow down feature annotation for user-specified crosswalks
**!** This PR should be merged after https://github.com/autowarefoundation/autoware.universe/pull/1528 is merged **!**
[pull request guidelines]: …
> docs(lanelet2_extension): add crosswalk safety slow down annotation instructions

- tmp/lanelet2_extension/docs/lanelet2_format_extension.md
- tmp/lanelet2_extension/include/lanelet2_extension/utility/query.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/visualization/visualization.hpp
- tmp/lanelet2_extension/lib/query.cpp
- tmp/lanelet2_extension/lib/visualization.cpp
Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>
Added visualization for the polygon tagged as `no_detection_area`
Related PR:
- https://github.com/autowarefoundation/autoware.universe/pull/1530
> feat: add visualization for no detection area

- tmp/lanelet2_extension/lib/visualization.cpp
Signed-off-by: Yukihiro Saito <yukky.saito@gmail.com>
In https://github.com/autowarefoundation/autoware.universe/pull/1234, I think it is included same refactorings. Then, this bug maybe mixed.  
Before PR1234
- https://github.com/autowarefoundation/autoware.universe/pull/1234/files#diff-d8edbc2230e14e187bfe6c35f8d8dbb36ef71aed79c971d35d347f67643bfcc5
After
- https://github.com/autowarefoundation/autoware_common/commit/88d942752ca9f68d4f51120d1dba59648fef24ef#diff-c57401de2ce50215e6c07092f71d4f641f64d470bdb489b07a8079153599d2a8
After all checkboxes are checked, anyone who has write …
> fix: traffic light visualization bug

- .github/workflows/check-build-depends.yaml
Please refer to https://github.com/autowarefoundation/autoware.universe/pull/1736.
> ci(check-build-depends): remove cancel workflow

- .github/workflows/check-build-depends.yaml
Fixup for https://github.com/autowarefoundation/autoware_common/pull/100.
> ci(check-build-depends): fix build-depends-repos

- .github/CODEOWNERS
- .github/CODEOWNERS-manual
- .github/sync-files-reverse-reference.yaml
- .github/sync-files.yaml
Same as https://github.com/autowarefoundation/autoware.universe/pull/1765.
- Remove autoware-maintainers from `CODEOWNERS-manual`.
- I've confirmed that `CODEOWNERS-manual` works.
- It's noisy for other maintainers.
- Sync `cancel-previous-workflows.yaml` from autowarefoundation/autoware.
- https://github.com/autowarefoundation/autoware/pull/2836
> ci: update minor CI settings

- .github/workflows/clang-tidy-pr-comments.yaml
Currently, errors occur when:
- There is no `fixes.yaml`.
- There is no artifact.
https://github.com/autowarefoundation/autoware_common/runs/7642971961?check_suite_focus=true#step:7:1
```
Run sed -i -e "s|/__w/|/home/runner/work/|g" /tmp/clang-tidy-result/fixes.yaml
sed: can't read /tmp/clang-tidy-result/fixes.yaml: No such file or directory
Error: Process completed with exit code 2.
```
https://github.com/autowarefoundation/autoware_common/runs/8107985999?check_suite_focus=true
```
Run gh run download 2961696016 -D /tmp
no valid artifacts found to download
Error: Process completed with exit code 1.
```
To fix them, check the existence of `fixes.yaml`.
Also, for https://github.com/autowarefoundation/autoware-github-actions/pull/192, we need to also run the workflow when it's failed.
The …
> ci(clang-tidy-pr-comments): add error handlings

- .github/workflows/clang-tidy-pr-comments-manually.yaml
`clang-tidy-pr-comments` would be noisy if there are a lot of warnings.
In that case, it's useful if we can disable the normal `clang-tidy-pr-comments` workflow and manually run the workflow at whatever timing developers want.
> ci(clang-tidy-pr-comments): add the workflow_dispatch version

- tmp/lanelet2_extension/lib/visualization.cpp
Signed-off-by: M. Fatih Cırıt <mfc@leodrive.ai>
OS: Ubuntu 22.04
ROS2: humble
Following the https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/ the lanelet map had the following error:
- `Multiple Markers in the same MarkerArray message had the same ns and id: (traffic_light_triangle, 0)`
**The reason for bug:**
- Multiple markers in the MarkerArray have the same ns and id
- It will only happen if your map has multiple traffic lights
**Solution:**
- For each marker pushed into the MarkerArray, increase the id by one.
**After this fix:**
The PR author **must** check the checkboxes below …
> fix(lanelet2_extension): traffic light id marker array visualization

- autoware_cmake/package.xml
Needed for ROS_DISTRO used in cmake/autoware_package.cmake.
> build: add exec_depend on ros_environment

- autoware_cmake/package.xml
Used in autoware_cmake/cmake/autoware_package.cmake.
> build: add ament_lint_auto dependency

- autoware_lint_common/README.md
Signed-off-by: M. Fatih Cırıt <mfc@leodrive.ai>
Follow up from https://github.com/autowarefoundation/autoware.core/issues/72#issuecomment-1415940370
`ADD_LINTER_TESTS` from `rosidl_generate_interfaces` adds unnecessary tests that are already covered by `pre-commit`.
This note will help developers avoid having similar problems like in the https://github.com/autowarefoundation/autoware.core/issues/72 …
> docs(autoware_lint_common): add note in the readme

- .github/sync-files.yaml
- .pre-commit-config.yaml
Use https://github.com/autowarefoundation/autoware/blob/main/.github/workflows/pre-commit-autoupdate.yaml instead. (Added the sync setting in https://github.com/autowarefoundation/autoware_common/pull/155/commits/4c43ef223e4b1098655fbcb392214a473b6bd686)
Related
- https://github.com/autowarefoundation/autoware.universe/pull/2838
- https://github.com/autowarefoundation/autoware/pull/3263
- https://github.com/autowarefoundation/autoware/pull/3264
> ci(pre-commit): disable autoupdate

- tmp/lanelet2_extension/include/lanelet2_extension/utility/utilities.hpp
- tmp/lanelet2_extension/lib/utilities.cpp
- tmp/lanelet2_extension/test/src/test_utilities.cpp
Signed-off-by: Maxime CLEMENT <maxime.clement@tier4.jp>
Update function `getExpandedLanelet` to set correct `z` values in the calculated expended lanelet.
| Without this PR | With this PR |
|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/78338830/211228870-2995bb49-40ea-4c69-a114-44b5bd3adfd9.png) | ![image](https://user-images.githubusercontent.com/78338830/211228767-2fb66dc6-6a97-49a1-b380-dfd8568653d4.png) |
After some quick profiling, it seems the added code takes at most 4μs so this should not impact performances.
You need to configure the `behavior_path_planner` to extend the lanelets by modifying `autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/drivable_area_expansion.param.yaml` and use non-zero parameter values …
> feat(lanelet2_extension): copy the z values in getExpandedLanelet

- tmp/lanelet2_extension/include/lanelet2_extension/utility/utilities.hpp
- tmp/lanelet2_extension/lib/utilities.cpp
Add two functions that calculate the lateral distance to a designated lanelet or the closest lanelet.
https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/src/util/lane_change/util.cpp#L359
https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/src/util/lane_change/util.cpp#L620
[pull request guidelines]: …
> feat(lanelet2_extension): add lateral distance calculation functions

- tmp/lanelet2_extension/include/lanelet2_extension/utility/query.hpp
- tmp/lanelet2_extension/lib/query.cpp
Signed-off-by: Mehmet Dogru <42mehmetdogru42@gmail.com>
closes https://github.com/autowarefoundation/autoware.universe/issues/2125
- https://github.com/autowarefoundation/autoware.universe/pull/2732
> feat(lanelet2_extension): consider lane-ego angle difference in lane following module

- tmp/lanelet2_extension/src/check_right_of_way.cpp
Signed-off-by: Mamoru Sobue <mamoru.sobue@tier4.jp>
I applied `clang-tidy` to the [prior PR](https://github.com/autowarefoundation/autoware_common/pull/114) and updated the code.
I could not suppress this warning eventually, but I think this is C-specific matter.
```
warning: do not use pointer arithmetic [cppcoreguidelines-pro-bounds-pointer-arithmetic]
const std::string map_path = std::string(argv[1]);
```
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribu …
> refactor: applied clang-tidy

- tmp/lanelet2_extension/lib/query.cpp
Signed-off-by: Taiga Takano [taiga.takano@tier4.jp](mailto:taiga.takano@tier4.jp)
If the size of the candidate_lanelets is 1, the "Find by Angle" task can be skipped.
This change speeds up the process as shown in the table below.
getClosestLanelet callback latency
|  PERCENTILE  |  BEFORE (us)  |  AFTER (us)  |
| ---- | ---- | ---- |
|  99%  |  42.5  |  33.3  |
|  90%  |  28.6  |  21.4  |
|  50%  |  15.7  |  10.3  |
> perf(lanelet2_extension): improve performance of getClosestLanelet

- tmp/lanelet2_extension/README.md
- tmp/lanelet2_extension/docs/lanelet2_format_extension.md
- tmp/lanelet2_extension/lib/autoware_osm_parser.cpp
- parser for local_x and local_y will be move to map_loader instead of loading in lanelet
https://github.com/autowarefoundation/autoware/issues/3427
https://github.com/autowarefoundation/autoware.universe/pull/3200
> feat: remove local x local y parser, move it to map_loader

- tmp/lanelet2_extension/include/lanelet2_extension/visualization/visualization.hpp
- tmp/lanelet2_extension/lib/visualization.cpp
visualize hatched road markings area in LL2.
Discussion for introducing hatched road markings area.
https://github.com/orgs/autowarefoundation/discussions/3414
can visualize the area with planning simulator
> feat: visualize hatched road markings

- tmp/lanelet2_extension/lib/query.cpp
- tmp/lanelet2_extension/lib/utilities.cpp
when segment is empty, accesing segment.back() causes node die.
psim, tier4 internal scenario test
> fix(lanelet2_extension): add exception handling for get closest segment

- tmp/lanelet2_extension/CMakeLists.txt
- tmp/lanelet2_extension/docs/lanelet2_format_extension.md
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/no_parking_area.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/utility/query.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/visualization/visualization.hpp
- tmp/lanelet2_extension/lib/no_parking_area.cpp
- tmp/lanelet2_extension/lib/query.cpp
- tmp/lanelet2_extension/lib/visualization.cpp
Currently `no_stopping_area` is used for the area where the ego vehicle cannot arrive when pull over. 
related: https://github.com/autowarefoundation/autoware.universe/pull/2492
But it is different from the original use of `no_stopping_area`, so create new `no_parking_area` and will use it in pull_over
the difference between `no_stopping_area` and `no_parking_area`
- `no_stopping_area` is an area where stopping for even a few seconds is not allowed. Stopping due to traffic congestion or waiting at traffic lights is also prohibited. This area is used by `no_stopping_area` module.
- `no_parking_area` is an area where only parking is prohibited. Stopping due to traffic congestion or waiting at traffic lights is not included. This area is used by parking module like `pull_over` of …
> feat(lanelet2_extension): add no parking area

- tmp/lanelet2_extension/CMakeLists.txt
Fixed build error happened on my environment:
Ubuntu: 22.04
kernel: 5.14.0-1054-oem
cmake: 3.26.3
g++ 11.3.0
ros-humble-lanelet2-core: 1.2.1-1jammy.20230511.171418
#183 
compiles on my machine as well
> fix(build): additional fix for build error in test

- autoware_cmake/cmake/autoware_package.cmake
`autoware_cmake` needs to be fixed for compiling old version of autoware due to the update of lanelet2-core.
cc @tkimura4 @shmpwk 
Beta branch of https://github.com/tier4/autoware.universe can be compiled.
> feat(autoware_cmake): add workaround for lanelet2@1.2.1

- tmp/lanelet2_extension/lib/visualization.cpp
Hatched road markings are visualized incorrectly without this PR. The boundary is not connected.
**Without this PR**
The bottom left object is hatched road markings, whose boundary is not fully connected.
**With this PR**
planning simulator
> fix: visualize hatched road markings

- tmp/lanelet2_extension/CMakeLists.txt
- tmp/lanelet2_extension/docs/crosswalk_regulatory_element.svg
- tmp/lanelet2_extension/docs/lanelet2_format_extension.md
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/autoware_traffic_light.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/crosswalk.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/utility/query.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/visualization/visualization.hpp
- tmp/lanelet2_extension/lib/autoware_traffic_light.cpp
- tmp/lanelet2_extension/lib/crosswalk.cpp
- tmp/lanelet2_extension/lib/query.cpp
- tmp/lanelet2_extension/lib/visualization.cpp
Add crosswalk regulatory element to lanelet extension library.
The format is [here](https://github.com/orgs/autowarefoundation/discussions/3036).
discussion: https://github.com/orgs/autowarefoundation/discussions/3036
> feat(lanelet2_extension): add crosswalk regulatory element

- tmp/lanelet2_extension/docs/lanelet2_format_extension.md
This PR is to update the link of `no_drivable_lane` module document link after changing its name and location in univerise.
> refactor(no_drivable_lane): updating no_drivable_lane doc link after refactoring updates

- .github/workflows/build-and-test.yaml
This PR reduces the disk space when building the autoware_common.
The need for reducing the disk space is originally from tier4/autoware.universe, and its CI is syncronized with this autoware_common, which is the reason why I casted the PR on autoware_common. 
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/4142
- [The disk space of building autoware.universe is nearly exhausted](https://github.com/autowarefoundation/autoware.universe/actions/runs/5433800625).
- Actually, [the disk space of the the forking repository is already exhausted](https://github.com/tier4/autoware.universe/actions/runs/5433801792/jobs/9881723716).
The PR reviewers **must** check the …
> ci(build-and-test): add free disk space

- .github/workflows/build-and-test.yaml
https://github.com/autowarefoundation/autoware_common/pull/197 causes the error because the CI cannot find `dotnet-*`.
https://github.com/autowarefoundation/autoware_common/actions/runs/5497109614/jobs/10017557487
To avoid this, this PR ignores installing `dotnet-*`.
CI passed at free disk space
https://github.com/autowarefoundation/autoware_common/actions/runs/5502951274/jobs/10027671593
Only build effect
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributi …
> ci(build-and-test): fix free disk space error

- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/Forward.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/autoware_traffic_light.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/crosswalk.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/detection_area.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/no_parking_area.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/no_stopping_area.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/road_marking.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/speed_bump.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/virtual_traffic_light.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/utility/message_conversion.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/utility/query.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/utility/route_checker.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/utility/utilities.hpp
- tmp/lanelet2_extension/lib/message_conversion.cpp
- tmp/lanelet2_extension/lib/query.cpp
- tmp/lanelet2_extension/lib/route_checker.cpp
- tmp/lanelet2_extension/lib/utilities.cpp
- tmp/lanelet2_extension/lib/visualization.cpp
- tmp/lanelet2_extension/test/src/test_message_conversion.cpp
- tmp/lanelet2_extension/test/src/test_query.cpp
- tmp/lanelet2_extension/test/src/test_route_checker.cpp
- tmp/lanelet2_extension/test/src/test_utilities.cpp
Add forward declaration header just as `lanelet2_core` `lanelet2_routing` package.
build passes
This PR adds forward declaration header
> feat(build)!: add forward declaration header

- tmp/lanelet2_extension/include/lanelet2_extension/utility/query.hpp
- tmp/lanelet2_extension/lib/query.cpp
`getCurrentLanelets` function takes an argument as `pose` however does not use orientation value in the function. Since it is redundant can be overloaded with `point` without affecting any algorithm uses that function. 
Later on code base can be refactored and the redundant getCurrentLanelets function can be removed.
No affect on existing structure
[pull request guidelines]: …
> refactor(lanelet2_extension): overload getCurrentLanelets with search point

- tmp/lanelet2_extension/lib/transverse_mercator_projector.cpp
- tmp/lanelet2_extension/test/src/test_projector.cpp
Fix Transverse Mercator Projector bug
Added a unit test
None
> fix(lanelet2_extensions): fix transverse mercator

- tmp/lanelet2_extension/lib/query.cpp
With the change, before setting an ego pose, "there are no lanelets close enough!" is printed a lot. Printing this every cycle seems not necessary which cannot be controlled by the application (node) side.
https://github.com/autowarefoundation/autoware.universe/pull/4941
planning simulator
Nothing
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pu …
> chore(lanelet2_extension): remove unnecessary print

- tmp/lanelet2_extension/include/lanelet2_extension/utility/query.hpp
- tmp/lanelet2_extension/lib/query.cpp
This PR makes enable to query curbstones from vector map.
The purpose of this feature is to publish curbstones as MarkerArray.
The background of this PR is below.
If the vector map contains a curbstone, we would like to check the position of the curbstone on rviz.
Because we need to know how much clearance do we have. 
I propose adding a marker array of curbstone.
https://github.com/autowarefoundation/autoware.universe/pull/4958
PSim
[contribution guidelines]: …
> feat(lanelet2_extensions): add query curbstones from vector map

- tmp/lanelet2_extension/lib/visualization.cpp
Display the id of traffic light regulatory  element id
none.
none.
> fix(visualization): display traffic reg elem id

- tmp/lanelet2_extension/include/lanelet2_extension/visualization/visualization.hpp
- tmp/lanelet2_extension/lib/visualization.cpp
Add util function to show intersection area.
Psim.
Nothing.
> feat(map_loader): show intersection areas

- .github/workflows/pre-commit-autoupdate.yaml
Part of:
- https://github.com/autowarefoundation/autoware/issues/3955
> ci(pre-commit-autoupdate): update the labels

- tmp/lanelet2_extension/README.md
- tmp/lanelet2_extension/include/lanelet2_extension/utility/message_conversion.hpp
- tmp/lanelet2_extension/lib/message_conversion.cpp
- tmp/lanelet2_extension/package.xml
- tmp/lanelet2_extension/test/src/test_message_conversion.cpp
- tmp/lanelet2_extension/test/src/test_route_checker.cpp
merge to autoware-msg branch:
replace autoware_auto_mapping_msg/msg/HADMapBin with autoware_map_msgs/msg/ LaneletMapBin
> feat(lanelet2_extension): replace autoware_auto_mapping_msg with autoware_map_msg

- tmp/lanelet2_extension/CMakeLists.txt
- tmp/lanelet2_extension/docs/lanelet2_format_extension.md
- tmp/lanelet2_extension/docs/localization_landmark.drawio.svg
- tmp/lanelet2_extension/include/lanelet2_extension/localization/landmark.hpp
- tmp/lanelet2_extension/lib/landmark.cpp
- tmp/lanelet2_extension/package.xml
Added localization landmark.
This new lanelet2 definition is related to the `landmark_based_localizer` in autoware.universe.
<https://github.com/autowarefoundation/autoware.universe/tree/main/localization/landmark_based_localizer>
Related pull request https://github.com/autowarefoundation/autoware.universe/pull/5803
It has been confirmed that the `logging_simulator` with `pose_source:=artag` runs with the same accuracy as before on AWSIM data with GT.
There is no effect except for `ar_tag_based_localizer`, and there is no change in the behavior of `ar_tag_based_localizer`. Just moved the definition code.
The PR author **must** check the checkboxes …
> feat(lanelet2_extension): added localization landmark

- tmp/lanelet2_extension/include/lanelet2_extension/visualization/visualization.hpp
- tmp/lanelet2_extension/lib/visualization.cpp
It was difficult to understand relationship between regulatry element id and road lanelet. In this PR, I fixed id visualization to show the id on stop line which is reffered by traffic regulatory element in order to make it easier to know related regulatory elements.
Psim
Nothing.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidel …
> fix(lanelet2_extension): improve traffic regulatory element id visualization

- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/autoware_traffic_light.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/crosswalk.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/detection_area.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/no_parking_area.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/no_stopping_area.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/road_marking.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/speed_bump.hpp
- tmp/lanelet2_extension/include/lanelet2_extension/regulatory_elements/virtual_traffic_light.hpp
- tmp/lanelet2_extension/lib/autoware_traffic_light.cpp
- tmp/lanelet2_extension/lib/crosswalk.cpp
- tmp/lanelet2_extension/lib/detection_area.cpp
- tmp/lanelet2_extension/lib/no_parking_area.cpp
- tmp/lanelet2_extension/lib/no_stopping_area.cpp
- tmp/lanelet2_extension/lib/road_marking.cpp
- tmp/lanelet2_extension/lib/speed_bump.cpp
- tmp/lanelet2_extension/lib/virtual_traffic_light.cpp
> To register a class, put
> RegisterRegulatoryElement<MyClass> regMyClass;
> somewhere in your cpp file.
Follow [this comment](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/include/lanelet2_core/primitives/RegulatoryElement.h#L375-L377) to move `RegisterRegulatoryElement` to cpp file. Also, remove redundant namespace and move the constructor to match the comment about object creation.
None
Check if lanelet2 map can be loaded using simple planning simulator.
None
None
None
After all checkboxes are checked, anyone who has write access can merge …
> refactor(lanelet2_extension): move RegisterRegulatoryElement to cpp file

- tmp/lanelet2_extension/lib/utilities.cpp
This PR prevents `getLineStringFromArcLength` from SIGSEGV.
When `linestring.size()` is 0, `linestring.size() - 1` can be inf because`linestring.size()` is unsigned .
https://github.com/autowarefoundation/autoware_common/blob/0dbf93e79f886ab5f1a25e94e72d8b4605fd3f0b/tmp/lanelet2_extension/lib/utilities.cpp#L219
As a result, `linestring[i]` can be invalid access.
https://github.com/autowarefoundation/autoware_common/blob/0dbf93e79f886ab5f1a25e94e72d8b4605fd3f0b/tmp/lanelet2_extension/lib/utilities.cpp#L220 
[TIER IV internal slack](https://star4.slack.com/archives/C0519A2HD1T/p1709277662657319)
We can reproduce this problem.
1. Download internal rosbag data.
[rosbag0](https://console.data-search.tier4.jp/projects/prd_jt/environments/393c3af9-bee1-42fc-85d7-f55f3d68a9e7/rosbags/c941b32d-538e …
> fix(lanelet2_extension): invalid access

- autoware_utils/package.xml
This PR adds a dependency for `libboost-system-dev` so that it can compile code that uses the Boost UUID library.
> build: fix Boost UUID dependency

- tmp/lanelet2_extension/lib/visualization.cpp
use `std::unordered_set<>::find` instead of `std::find` to improve lookup speed.
See https://stackoverflow.com/questions/71062930/how-does-stdfind-works-with-stdset
> perf(lanelet2_extension): use std::unordered_set<>::find instead of std::find

- .github/workflows/build-and-test.yaml
Show disk space at the end of the task.
Already used in autoware.universe/.github/workflows/build-and-test.yaml
https://github.com/autowarefoundation/autoware.universe/blob/457771919d907aebd1ffe66c4d6a8b3588b0b458/.github/workflows/build-and-test.yaml#L66-L67
> ci(build-and-test): show disk space in the end

- .github/workflows/build-and-test-arm64.yaml
- .github/workflows/build-and-test-differential-arm64.yaml
- .github/workflows/build-and-test-differential.yaml
- .github/workflows/build-and-test.yaml
- .github/workflows/clang-tidy-differential.yaml
- Split clang-tidy into its own workflow
- Rename `-self-hosted` jobs to `-arm64`
- Remove `jlumbroso/free-disk-space@v1.3.1` because it has no effect in containers.
- Upgrade `actions/checkout@v3` to `v4`
- Run `-differential` jobs on `reopened` too.
- Add tag dependency to both `build-and-main-differential` and `clang-tidy-differential` workflows.
- Make use of `make-sure-label-is-present.yaml` reusable workflow since it supports multiple labels.
- See: https://github.com/autowarefoundation/autoware-github-actions/pull/301
- For `build-and-main` jobs:
- add `fetch-depth: 1` since they don't check for modified packages
- For `build-and-main-differential` jobs:
- add `Set PR fetch depth` step to fetch only the PR commits.
All the differential jobs are tested with the labels and passed on …
> ci: overhaul build-and-test derivatives and split clang-tidy

- tmp/lanelet2_extension/test/src/test_regulatory_elements.cpp
As ROS 2 jazzy will be released soon, this PR will fix build error found in rolling build environment.
- Add `boost/optional/optional_io.hpp` to some source files. This header file is required by newer version of Boost.
`colcon test` on humble distribution does not show new error.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pul …
> fix: boost optional build error on rolling environment

- tmp/lanelet2_extension/docs/lanelet2_format_extension.md
- tmp/lanelet2_extension/include/lanelet2_extension/utility/utilities.hpp
- tmp/lanelet2_extension/lib/utilities.cpp
- tmp/lanelet2_extension/test/src/test_utilities.cpp
- tmp/lanelet2_extension_python/src/utility.cpp
The Autoware's usage of the centerline has several limitations.
By introducing a `waypoints` flag in the `overwriteLaneletsCenterline` function to handle the centerline, the limitations are solved.
Please see the document in this PR in detail.
NOTE: This PR includes the fix for clang-tidy in the lanelet2_extension_python package.
Unit test
Nothing
[pull request guidelines]: …
> feat(lanelet2_extension): overwriteLaneletsCenterline supports "waypoints"
