autowarefoundation/autoware_common

autoware_lint_common/CMakeLists.txt, autoware_lint_common/README.md, autoware_lint_common/package.xml
#1
Add autoware_lint_common for formatting.
=> feat: add autoware_lint_common

.github/workflows/build-and-test-arm.yaml, .github/workflows/build-and-test.yaml
The same as https://github.com/autowarefoundation/autoware.universe/pull/297.
=> ci: split ARM scheduled job

.github/workflows/build-and-test-pr.yaml, .github/workflows/build-and-test.yaml
Fix https://github.com/autowarefoundation/autoware_common/runs/5016608295?check_suite_focus=true
Signed-off-by: Keisuke Shima <19993104+KeisukeShima@users.noreply.github.com>
=> fix(build-and-test): add file check action

.github/workflows/build-and-test-pr.yaml, .github/workflows/build-and-test.yaml
Fixes https://github.com/autowarefoundation/autoware_common/pull/15#discussion_r797209662
Signed-off-by: Keisuke Shima <19993104+KeisukeShima@users.noreply.github.com>
=> fix(build-and-test): fix argument of check-file-existence

.github/workflows/build-and-test.yaml
https://github.com/autowarefoundation/autoware_common/pull/23 don't work. This PR fix it.
=> ci(build-and-test): fix to work only on the default branch

.github/workflows/build-and-test-differential-self-hosted.yaml, .github/workflows/build-and-test-differential.yaml, .github/workflows/build-and-test-self-hosted.yaml, .github/workflows/spell-check-differential.yaml
=> ci: update CI workflows

.github/sync-files-reverse-reference.yaml, .github/sync-files.yaml
=> chore: update sync-files settings

.github/sync-files-reverse-reference.yaml, .github/workflows/clang-tidy-pr-comments.yaml
Added by https://github.com/autowarefoundation/autoware.universe/pull/375.
=> chore: sync clang-tidy-pr-comments.yaml

.github/workflows/build-and-test-differential-self-hosted.yaml, .github/workflows/build-and-test-differential.yaml, .github/workflows/build-and-test-self-hosted.yaml, .github/workflows/build-and-test.yaml, .github/workflows/check-build-depends.yaml, .github/workflows/sync-files-reverse-reference.yaml, .github/workflows/sync-files.yaml
Related: https://github.com/autowarefoundation/autoware/pull/74
=> ci: use v1 instead of tier4/proposal

.github/workflows/build-and-test-self-hosted.yaml, .github/workflows/build-and-test.yaml, .github/workflows/sync-files.yaml
Same as https://github.com/autowarefoundation/autoware/pull/75.
=> ci: change cron schedules

.pre-commit-config.yaml
Signed-off-by: Takagi, Isamu <isamu.takagi@tier4.jp>
=> chore: update tier4/pre-commit-hooks-ros

.github/sync-files-reverse-reference.yaml, .github/workflows/build-and-test-differential.yaml, .github/workflows/build-and-test.yaml, codecov.yaml
Signed-off-by: Keisuke Shima <19993104+KeisukeShima@users.noreply.github.com>
Related https://github.com/autowarefoundation/autoware.universe/pull/648
=> ci(build-and-test): add codecov flags

.github/workflows/build-and-test-with-reverse-depends.yaml
Since this repository is referenced by many repositories, it's good to check the build of the reverse depends.
=> ci: add build-and-test-with-reverse-depends.yaml

autoware_cmake/cmake/autoware_package.cmake
A follow-up for #76.
There are still some errors left after merging https://github.com/autowarefoundation/autoware.universe/pull/978.
https://github.com/autowarefoundation/autoware/runs/6614506073?check_suite_focus=true#step:6:5365
Since it's hard to check all packages, I'd like to add Eigen as a system include here.
As I removed `find_package(Eigen3)` from #76, I believe this doesn't add any unnecessary dependency that Esteve-san was concerned about.
With a debug message added like this,
```
message("#### ${EIGEN3_INCLUDE_DIR}")
include_directories(SYSTEM
${EIGEN3_INCLUDE_DIR}
)
```
- interpolation (Indirect Eigen dependency through tier4_autoware_utils)
```
Starting >>> interpolation
--- stderr: interpolation                                
---
Finished <<< interpolation [13.5s]
```
- …
=> feat(autoware_cmake): set system includes after ament_auto_find_build_dependencies

.github/CODEOWNERS-manual, .github/sync-files-reverse-reference.yaml, .github/workflows/update-codeowners-from-packages.yaml
Same as https://github.com/autowarefoundation/autoware.universe/pull/1619.
=> ci: add update-codeownders-from-packages.yaml

.github/workflows/check-build-depends.yaml
It should be checked with multiple ROS distros.
=> ci(check-build-depends): support matrix

.github/sync-files-reverse-reference.yaml, .github/workflows/build-and-test-differential.yaml
Please refer to https://github.com/autowarefoundation/autoware.universe/pull/1736.
=> chore(sync-files): sync cancel-previous-workflows.yaml

.github/workflows/cancel-previous-workflows.yaml
Please refer to https://github.com/autowarefoundation/autoware.universe/pull/1741.
=> ci(cancel-previous-workflows): use pull_request_target

.github/sync-files-reverse-reference.yaml
=> ci(sync-files-reverse-reference): update sync settings

.github/sync-files-reverse-reference.yaml
Related: https://github.com/autowarefoundation/autoware.universe/pull/2217
=> ci(sync-files): sync clang-tidy-pr-comments-manually.yaml

.github/sync-files-reverse-reference.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/2348.
=> ci(sync-files): sync .pre-commit-config.yaml

build_depends.repos, tmp/lanelet2_extension/include/lanelet2_extension/utility/route_checker.hpp, tmp/lanelet2_extension/lib/route_checker.cpp, tmp/lanelet2_extension/package.xml, tmp/lanelet2_extension/test/src/test_route_checker.cpp
Signed-off-by: kosuke55 <kosuke.tnp@gmail.com>
Replace HADMap of autoware_auto_planning_msg with Lanelet of autoware_planning_msgs.
LaneLetRoute has uuid and I want to use it in planning modules. Please refer to https://github.com/autowarefoundation/autoware/discussions/2983 for details.
- universe
-  https://github.com/autowarefoundation/autoware.universe/pull/2356
- autoware_launch
- https://github.com/tier4/autoware_launch/pull/571   
- port PR of auto_msgs to autoware_msgs
- https://github.com/autowarefoundation/autoware_msgs/pull/33
- Rename to Lanelet
-  https://github.com/autowarefoundation/autoware_msgs/pull/41  
- Add uuid to Lanelet
- https://github.com/autowarefoundation/autoware_msgs/pull/42
psim
The PR …
=> feat!: replace HADMap with Lanelet

.github/workflows/build-and-test-differential-self-hosted.yaml, .github/workflows/build-and-test-differential.yaml, .github/workflows/build-and-test-self-hosted.yaml, .github/workflows/build-and-test-with-reverse-depends.yaml, .github/workflows/build-and-test.yaml, .github/workflows/check-build-depends.yaml
For https://github.com/autowarefoundation/autoware/issues/3083.
=> ci: remove Galactic CI workflows

autoware_cmake/package.xml, autoware_lint_common/package.xml, autoware_utils/package.xml
Added myself (Esteve Fernandez) as a maintainer
=> chore: added esteve as a maintainer

.pre-commit-config.yaml
Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>
See https://github.com/autowarefoundation/autoware.universe/pull/2777
=> ci(pre-commit): upgrade isort version

tmp/lanelet2_extension/lib/visualization.cpp
Signed-off-by: tomoya.kimura <tomoya.kimura@tier4.jp>
Set frame_locked to false for the improvement of rviz's fps.
frame_locked: true
14Hz
frame_locked: false
31Hz
(
CPU: i9-9900K @3.60GHz
GPU: GeForce RTX 2080 Ti
)
=> feat(lanalet2_extension): set frame_locked to false

.github/workflows/clang-tidy-pr-comments-manually.yaml, .github/workflows/clang-tidy-pr-comments.yaml
See https://github.com/autowarefoundation/autoware-github-actions/issues/188.
=> ci: replace set-output with $GITHUB_OUTPUT

tmp/lanelet2_extension/docs/lanelet2_format_extension.md
brief documentation for https://github.com/autowarefoundation/autoware_common/pull/178
=> docs(lanelet2_extension): hatched road markings

tmp/lanelet2_extension/lib/utilities.cpp, tmp/lanelet2_extension/lib/visualization.cpp
change log level from error to warn for visualization
run psim
=> chore(lanelet2_extension): change log level from error to warn for visualization

tmp/lanelet2_extension/docs/lanelet2_format_extension.md
This PR is one of group of PRs for providing a solution for the idea discussed [here](https://github.com/orgs/autowarefoundation/discussions/3275).
This PR is to update the lanelet2_format_extention documentation with the new optional invalid lanelet tag
- [Discussion Link](https://github.com/orgs/autowarefoundation/discussions/3275)
- [Issue Link](https://github.com/autowarefoundation/autoware/issues/3308)
- [autoware_documentation](https://github.com/autowarefoundation/autoware-documentation/pull/337)
- [tier4/tier4_autoware_msgs - part I](https://github.com/tier4/tier4_autoware_msgs/pull/76) :heavy_check_mark: 
- [tier4/tier4_autoware_msgs - part II](https://github.com/tier4/tier4_autoware_msgs/pull/87) :heavy_check_mark: 
- [autoware_adapi_msgs](https://github.com/autowarefoundation/au …
=> feat: handle invalid lanelet

.pre-commit-config.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/4002.
=> ci(pre-commit): add check-jsonschema

tmp/lanelet2_extension/include/lanelet2_extension/utility/utilities.hpp, tmp/lanelet2_extension/lib/utilities.cpp
move `combineLanelets` out of unnamed namespace to use this in other files.
https://github.com/autowarefoundation/autoware.universe/issues/4078
psim
=> feat(lanelet2_extension): move combineLanelets unnamed namespace

autoware_cmake/package.xml, autoware_lint_common/package.xml, autoware_utils/package.xml
Since I don't touch the code anymore, update the maintainers.
=> chore: update maintainer

tmp/lanelet2_extension/CMakeLists.txt, tmp/lanelet2_extension/README.md, tmp/lanelet2_extension/include/lanelet2_extension/projection/transverse_mercator_projector.hpp, tmp/lanelet2_extension/lib/transverse_mercator_projector.cpp
I would like to add Transverse Mercator Projection method for Autoware.
https://github.com/orgs/autowarefoundation/discussions/3582
Loaded a sample lanelet2 map with a custom pointcloud map which is also projected with Transverse Mercator Projection, and confirmed that pcd and lanelet appear on RViz and sample rosbag runs with logging_simulator.
Note that this feature is not implemented in Autoware Universe yet. The above procedure has been done in customized Autoware Universe that is soon to be implemented in public.
N/A
After all checkboxes are checked, anyone who has write access …
=> feat(lanelet2_extensions): add transverse mercator projector

tmp/lanelet2_extension/docs/crosswalk_traffic_light.svg, tmp/lanelet2_extension/docs/lanelet2_format_extension.md
Add description how to define traffic light regulatory element for crosswalk.
Nothing.
Nothing.
=> docs(lanelet2_extension): add brief description for crosswalk traffic light

tmp/lanelet2_extension/include/lanelet2_extension/utility/query.hpp, tmp/lanelet2_extension/lib/query.cpp
Add function of `getAllFences()`.
this change is necessary for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/5356)
=> feat(lanelet2_extention): add getAllFences

.github/workflows/update-codeowners-from-packages.yaml
Changes the PR labels to conform with the following issue:
- https://github.com/autowarefoundation/autoware/issues/3955
=> ci(update-codeowners-from-packages): update labels

tmp/lanelet2_extension/include/lanelet2_extension/visualization/visualization.hpp, tmp/lanelet2_extension/lib/visualization.cpp
update function for https://github.com/autowarefoundation/autoware.universe/pull/5880
See https://github.com/autowarefoundation/autoware.universe/pull/5880.
None
=> chore(lanelet2_extension): add namespace arg for lanelet id visualization

tmp/lanelet2_extension/package.xml
=> chore(lanelet2_extension): add maintainer in lanelet2_extension

.markdownlint.yaml
=> ci(markdownlint.yaml): allow images without alt text

README.md
Update README before archiving the repository.
Check: https://github.com/orgs/autowarefoundation/discussions/4671
=> docs: add notice for archiving the repository
